- name: Ensure AWS credentials for root
  file:
    path: "/root/.aws"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Write AWS credentials for root
  copy:
    dest: "/root/.aws/credentials"
    content: |
      [default]
      aws_access_key_id = {{ aws_access_key_id }}
      aws_secret_access_key = {{ aws_secret_access_key }}
    mode: '0600'
    owner: root
    group: root


- name: Copy update-dns.sh to /usr/local/bin
  copy:
    src: update-dns.sh
    dest: /usr/local/bin/update-dns.sh
    owner: root
    group: root
    mode: '0755'

- name: Ensure /etc/rc.local exists
  copy:
    dest: /etc/rc.local
    content: |
      #!/bin/bash
      /usr/local/bin/update-dns.sh &
      exit 0
    owner: root
    group: root
    mode: '0755'

