FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-requests \
    python3-consul \
    ansible \
    curl \
    jq

USER jenkins

