---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true

- name: Install PyMySQL via apt
  apt:
    name: python3-pymysql
    state: present

- name: Create MySQL user using shell as root
  shell: |
    mysql -e "CREATE USER IF NOT EXISTS 'devops_user'@'%' IDENTIFIED BY 'SuperSecret123';"
    mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'devops_user'@'%' WITH GRANT OPTION;"
    mysql -e "FLUSH PRIVILEGES;"
  become: true

- name: Create devops_db database
  shell: |
    mysql -e "CREATE DATABASE IF NOT EXISTS devops_db;"
  become: true

