---
- name: Create users
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    create_home: yes
  loop: "{{ users }}"

- name: Add users to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }} '
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
  loop: "{{ users }}"

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ users }}"

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ users }}"

- name: Copy public key to authorized_keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ public_key }}"
  loop: "{{ users }}"

- name: Generate hello message for each user
  template:
    src: hello_message.j2
    dest: "/home/{{ item }}/hello.txt"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop: "{{ users }}"


